context:
  version: "0.1.8"

package:
  name: tsshd
  version: ${{ version }}

source:
  url: https://github.com/trzsz/tsshd/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 1d19f99a95f19933d8058df1209b421400eaca8c2bf2e045747c8f6c68887d56

build:
  number: 0
  script:
    - go-licenses save ./cmd/tsshd --save_path ./library_licenses
    - if: unix
      then: go build -v -trimpath -o $PREFIX/bin/tsshd -ldflags="-s -w" ./cmd/tsshd
      else: go build -v -trimpath -o %LIBRARY_BIN%\tsshd.exe -ldflags="-s -w" .\cmd\tsshd

requirements:
  build:
    - "{% if target_platform == 'win-arm64' %} go {% else %} ${{ compiler('go-nocgo') }} {% endif %}"
    - go-licenses

tests:
  - script:
      - tsshd -V
  - package_contents:
      bin:
        - tsshd
      strict: true

about:
  homepage: https://trzsz.github.io/tsshd
  summary: "UDP-based SSH server with roaming support"
  license: MIT
  license_file:
    - LICENSE
    - library_licenses/
  repository: https://github.com/trzsz/tsshd

extra:
  recipe-maintainers:
    - lonnywong
